main: org.cubeville.cvlwcutil.CVLWCUtil
name: CVLWCUtil
version: 0.1
api-version: 1.16
description: 'CVLWCUtil Plugin'
author: ToeMan_
depend: [WorldEdit,CVTools,LWC]
commands:
  cvlwcutil:
    permission: CVLWCUtil.admin

permissions:
  CVLWCUtil.admin:
    description: Permissions to all commands
    default: op